version: '3.8'
services:
  stats-server:
    build: ./statistics/stats-service
    image: stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstats
      - SPRING_DATASOURCE_POSTGRES_USER=root
      - SPRING_DATASOURCE_POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/ewmservice
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=password
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmservice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root